language: python
python:
  - "2.7"
  - "3.6"
#  - "3.7-dev"  # 3.7 development branch, disabled for now because of errors due to numpy output formatting in doctests
install:
  - pip install pathlib
  - python setup.py install
script:
  - pytest --doctest-modules
